### ISSUE TITLE
Content of scripts folder

### ISSUE THREAD

**Issue by Jatc252** [Ccode-lang/LethalCompanyUnityTemplate-SirenHead#1]
It appears that you may have uploaded all of the game's code under the [Assembly scripts folder](https://github.com/Ccode-lang/LethalCompanyUnityTemplate-SirenHead/tree/master/Assets/Scripts/Assembly-CSharp). I would investigate as you may be breaching copyright with this.

**Comment by Ccode-lang** [comment]
No, they're stubs. It's fine
